<?php

namespace ContainerB7upPX8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Questions' shared autowired service.
     *
     * @return \App\Controller\Questions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Questions.php';

        $container->services['App\\Controller\\Questions'] = $instance = new \App\Controller\Questions();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Questions', $container));

        return $instance;
    }
}
