<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH9LbXPm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH9LbXPm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH9LbXPm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH9LbXPm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH9LbXPm\App_KernelDevDebugContainer([
    'container.build_hash' => 'H9LbXPm',
    'container.build_id' => '2089072f',
    'container.build_time' => 1666618660,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH9LbXPm');
