<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB7upPX8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB7upPX8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB7upPX8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB7upPX8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB7upPX8\App_KernelDevDebugContainer([
    'container.build_hash' => 'B7upPX8',
    'container.build_id' => '985fa2c5',
    'container.build_time' => 1666581958,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB7upPX8');
