<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'question' => [['wildcard'], ['_controller' => 'App\\Controller\\Questions::show'], [], [['variable', '/', '[^/]++', 'wildcard', true], ['text', '/questions']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\SymfonyController::home'], [], [['text', '/']], [], [], []],
    'yes' => [[], ['_controller' => 'App\\Controller\\Yes::yes'], [], [['text', '/yes']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
